export default [
  {
    id: 1,
    title: "Who is the good boy?",
    description: "The answer may surprise you! it is you.",
    price: 1000,
    coverImg: "pitbull cute.jpeg",
    stats: {
      rating: 5.0,
      reviewCount: 6,
    },
    location: "Online",
    openSpots: 10,
  },
  {
    id: 2,
    title: "How to chase the mailman!",
    description: "Run until he leaves!",
    price: 500,
    coverImg: "beagle.jpeg",
    stats: {
      rating: 5.0,
      reviewCount: 30,
    },
    location: "USA",
    openSpots: 0,
  },
  {
    id: 3,
    title: "where should you hide the bone",
    description: "Good backyard spots",
    price: 700,
    coverImg: "corgi.jpeg",
    stats: {
      rating: 4.8,
      reviewCount: 2,
    },
    location: "NOR",
    openSpots: 3,
  },
  {
    id: 4,
    title: "How to ask for new toys!",
    description: "Barking...",
    price: 100,
    coverImg: "dog selfie.jpeg",
    stats: {
      rating: 4.8,
      reviewCount: 2,
    },
    location: "AUS",
    openSpots: 0,
  },
  {
    id: 5,
    title: "How to ask for new toys!",
    description: "Barking...",
    price: 100,
    coverImg: "little fluff.jpeg",
    stats: {
      rating: 4.6,
      reviewCount: 2,
    },
    location: "NZ",
    openSpots: 3,
  },
  {
    id: 6,
    title: "Who is the good boy?",
    description: "The answer may surprise you! it is you.",
    price: 1000,
    coverImg: "pitbull cute.jpeg",
    stats: {
      rating: 5.0,
      reviewCount: 6,
    },
    location: "Online",
    openSpots: 10,
  },
  {
    id: 7,
    title: "How to chase the mailman!",
    description: "Run until he leaves!",
    price: 500,
    coverImg: "beagle.jpeg",
    stats: {
      rating: 5.0,
      reviewCount: 30,
    },
    location: "USA",
    openSpots: 0,
  },
  {
    id: 8,
    title: "Where should you hide the bone",
    description: "Good backyard spots",
    price: 700,
    coverImg: "corgi.jpeg",
    stats: {
      rating: 4.8,
      reviewCount: 2,
    },
    location: "NOR",
    openSpots: 3,
  },
  {
    id: 9,
    title: "How to ask for new toys!",
    description: "Barking...",
    price: 100,
    coverImg: "dog selfie.jpeg",
    stats: {
      rating: 4.8,
      reviewCount: 2,
    },
    location: "AUS",
    openSpots: 0,
  },
  {
    id: 10,
    title: "How to ask for new toys!",
    description: "Barking...",
    price: 100,
    coverImg: "little fluff.jpeg",
    stats: {
      rating: 4.6,
      reviewCount: 2,
    },
    location: "NZ",
    openSpots: 3,
  },
  {
    id: 11,
    title: "Who is the good boy?",
    description: "The answer may surprise you! it is you.",
    price: 1000,
    coverImg: "pitbull cute.jpeg",
    stats: {
      rating: 5.0,
      reviewCount: 6,
    },
    location: "Online",
    openSpots: 10,
  },
  {
    id: 12,
    title: "How to chase the mailman!",
    description: "Run until he leaves!",
    price: 500,
    coverImg: "beagle.jpeg",
    stats: {
      rating: 5.0,
      reviewCount: 30,
    },
    location: "USA",
    openSpots: 0,
  },
  {
    id: 13,
    title: "Where should you hide the bone",
    description: "Good backyard spots",
    price: 700,
    coverImg: "corgi.jpeg",
    stats: {
      rating: 4.8,
      reviewCount: 2,
    },
    location: "NOR",
    openSpots: 3,
  },
  {
    id: 14,
    title: "How to ask for new toys!",
    description: "Barking...",
    price: 100,
    coverImg: "dog selfie.jpeg",
    stats: {
      rating: 4.8,
      reviewCount: 2,
    },
    location: "AUS",
    openSpots: 0,
  },
  {
    id: 15,
    title: "How to ask for new toys!",
    description: "Barking...",
    price: 100,
    coverImg: "little fluff.jpeg",
    stats: {
      rating: 4.6,
      reviewCount: 2,
    },
    location: "NZ",
    openSpots: 3,
  },
];
